baseURL = "https://example.com/"
title = "Tutoriais"
googleAnalytics = "UA-123-456-789"
theme = "github-style"
copyright = "© 2019. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"

[params]
  author = "Allan Alvarenga"
  description = "Tutoriais feitos por mim"
  github = "allan296"
  facebook = "example"
  twitter = "example"
  misskey = "user profile url"
  mastodon = "user profile url"
  email = "allan.baptista@gmail.com"
  utterances = "example/example.github.io"
  avatar = "files/foto_perfil.jpg"
  url = "https://allanalvarenga.netlify.com/"